# Generated by Django 3.2 on 2024-11-08 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
