# Generated by Django 3.2 on 2024-11-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0004_auto_20241108_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=125)),
                ('password', models.CharField(max_length=125)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
